export const ROUTES = {
  designSystem: '/design-system',
  admin: {
    root: '/admin',
    login: '/admin/login',
    dashboard: '/admin/dashboard',
    resources: '/admin/resources',
    resourceNew: '/admin/resources/new',
    resourceDetail: (id: string | number) => `/admin/resources/${id}`,
    resourceEdit: (id: string | number) => `/admin/resources/${id}/edit`,
    reservations: '/admin/reservations',
    reservationDetail: (id: string | number) => `/admin/reservations/${id}`,
    rentals: '/admin/rentals',
    rentalDetail: (id: string | number) => `/admin/rentals/${id}`,
    inspections: '/admin/inspections',
    inspectionNew: '/admin/inspections/new',
    inspectionDetail: (id: string | number) => `/admin/inspections/${id}`,
    inspectionEdit: (id: string | number) => `/admin/inspections/${id}/edit`,
    users: '/admin/users',
    userDetail: (id: string | number) => `/admin/users/${id}`,
    userEdit: (id: string | number) => `/admin/users/${id}/edit`,
    statistics: '/admin/statistics',
    settings: '/admin/settings',
  },
  user: {
    home: '/',
    login: '/login',
    resources: '/resources',
    resourceDetail: (id: string | number) => `/resources/${id}`,
    reservations: '/reservations',
    reservationHistory: '/reservations/history',
    reservationHistoryDetail: (id: string | number) => `/reservations/history/${id}`,
    rentals: '/rentals',
    rentalDetail: (id: string | number) => `/rentals/${id}`,
    notifications: '/notifications',
    notificationDetail: (id: string | number) => `/notifications/${id}`,
    mypage: '/mypage',
    mypageEdit: '/mypage/edit',
  },
} as const
